<?php

namespace Database\Seeders;

use App\Models\Service;
use Illuminate\Database\Seeder;

class ServicesSeeder extends Seeder
{
    /**
     * 17 Jagoan dengan harga 3 sesi (Seharian, Pagi, Sore).
     * Di GoKang asli, harga pagi = harga sore (sama).
     */
    public function run(): void
    {
        $services = [
            [
                'code' => 'JAGOAN_CAT',
                'name' => 'Jagoan Cat',
                'slug' => 'jagoan-cat',
                'description' => 'Bantu membuang cat lama, melakukan cat dasar, finishing, dan segala permasalahan cat lainnya. Melayani cat di dinding, plafon, pintu dan jendela kayu.',
                'icon_url' => '/icons/jagoan-cat.svg',
                'price_full_day' => 259000,
                'price_morning' => 199000,
                'price_afternoon' => 199000,
                'service_type' => 'daily',
                'sort_order' => 1,
            ],
            [
                'code' => 'JAGOAN_KERAMIK',
                'name' => 'Jagoan Keramik',
                'slug' => 'jagoan-keramik',
                'description' => 'Ahli bongkar pasang keramik dan porselen untuk lantai maupun dinding secara presisi.',
                'icon_url' => '/icons/jagoan-keramik.svg',
                'price_full_day' => 264000,
                'price_morning' => 204000,
                'price_afternoon' => 204000,
                'service_type' => 'daily',
                'sort_order' => 2,
            ],
            [
                'code' => 'JAGOAN_LISTRIK',
                'name' => 'Jagoan Listrik',
                'slug' => 'jagoan-listrik',
                'description' => 'Siap bantu instalasi listrik, memasang stop kontak, fitting lampu dan permasalahan listrik lainnya.',
                'icon_url' => '/icons/jagoan-listrik.svg',
                'price_full_day' => 259000,
                'price_morning' => 199000,
                'price_afternoon' => 199000,
                'service_type' => 'daily',
                'sort_order' => 3,
            ],
            [
                'code' => 'KENEK',
                'name' => 'Kenek (Ast. Jagoan)',
                'slug' => 'kenek',
                'description' => 'Asisten tukang agar pekerjaan lebih cepat selesai.',
                'icon_url' => '/icons/kenek.svg',
                'price_full_day' => 209000,
                'price_morning' => 163000,
                'price_afternoon' => 163000,
                'service_type' => 'daily',
                'sort_order' => 4,
            ],
            [
                'code' => 'JAGOAN_ALUMINIUM',
                'name' => 'Jagoan Aluminium Aksesoris',
                'slug' => 'jagoan-aluminium',
                'description' => 'Tenaga ahli untuk berbagai pekerjaan seputar pintu dan jendela aluminium.',
                'icon_url' => '/icons/jagoan-aluminium.svg',
                'price_full_day' => 259000,
                'price_morning' => 199000,
                'price_afternoon' => 199000,
                'service_type' => 'daily',
                'sort_order' => 5,
            ],
            [
                'code' => 'JAGOAN_BATU',
                'name' => 'Jagoan Batu',
                'slug' => 'jagoan-batu',
                'description' => 'Siap bereskan segala pekerjaan dinding, tembok, batu alam dan conblock.',
                'icon_url' => '/icons/jagoan-batu.svg',
                'price_full_day' => 259000,
                'price_morning' => 199000,
                'price_afternoon' => 199000,
                'service_type' => 'daily',
                'sort_order' => 6,
            ],
            [
                'code' => 'JAGOAN_PIPA',
                'name' => 'Jagoan Pipa',
                'slug' => 'jagoan-pipa',
                'description' => 'Perbaiki pipa bocor, saluran pipa macet, pipa air bersih dan kotor.',
                'icon_url' => '/icons/jagoan-pipa.svg',
                'price_full_day' => 299000,
                'price_morning' => 239000,
                'price_afternoon' => 239000,
                'service_type' => 'daily',
                'sort_order' => 7,
            ],
            [
                'code' => 'JAGOAN_WATERPROOFING',
                'name' => 'Jagoan Waterproofing',
                'slug' => 'jagoan-waterproofing',
                'description' => 'Betulkan genteng/atap atau bagian rumah lainnya yang rentan bocor.',
                'icon_url' => '/icons/jagoan-waterproofing.svg',
                'price_full_day' => 299000,
                'price_morning' => 239000,
                'price_afternoon' => 239000,
                'service_type' => 'daily',
                'sort_order' => 8,
            ],
            [
                'code' => 'JAGOAN_GALI',
                'name' => 'Jagoan Gali',
                'slug' => 'jagoan-gali',
                'description' => 'Tukang untuk segala keperluan bergali.',
                'icon_url' => '/icons/jagoan-gali.svg',
                'price_full_day' => 259000,
                'price_morning' => 199000,
                'price_afternoon' => 199000,
                'service_type' => 'daily',
                'sort_order' => 9,
            ],
            [
                'code' => 'JAGOAN_BESI',
                'name' => 'Jagoan Besi (Las)',
                'slug' => 'jagoan-besi',
                'description' => 'Ahlinya permasalahan ngelas besi untuk rumahmu.',
                'icon_url' => '/icons/jagoan-besi.svg',
                'price_full_day' => 264000,
                'price_morning' => 204000,
                'price_afternoon' => 204000,
                'service_type' => 'daily',
                'sort_order' => 10,
            ],
            [
                'code' => 'JAGOAN_GENTENG',
                'name' => 'Jagoan Genteng',
                'slug' => 'jagoan-genteng',
                'description' => 'Tukang ahli masalah genteng dan atap.',
                'icon_url' => '/icons/jagoan-genteng.svg',
                'price_full_day' => 299000,
                'price_morning' => 239000,
                'price_afternoon' => 239000,
                'service_type' => 'daily',
                'sort_order' => 11,
            ],
            [
                'code' => 'JAGOAN_PLAFON',
                'name' => 'Jagoan Plafon',
                'slug' => 'jagoan-plafon',
                'description' => 'Bantu selesaikan masalah plafon rusak, berlumut, roboh dan lainnya.',
                'icon_url' => '/icons/jagoan-plafon.svg',
                'price_full_day' => 259000,
                'price_morning' => 199000,
                'price_afternoon' => 199000,
                'service_type' => 'daily',
                'sort_order' => 12,
            ],
            [
                'code' => 'KONSULTAN',
                'name' => 'Konsultan',
                'slug' => 'konsultan',
                'description' => 'Bantu menentukan jumlah material dan tukang yang cocok untuk proyekmu.',
                'icon_url' => '/icons/konsultan.svg',
                'price_full_day' => 0,
                'price_morning' => 249000,
                'price_afternoon' => 249000,
                'service_type' => 'consultant',
                'sort_order' => 13,
            ],
            [
                'code' => 'JAGOAN_SANITAIR',
                'name' => 'Jagoan Sanitair',
                'slug' => 'jagoan-sanitair',
                'description' => 'Andalan pasang wastafel, kloset, keran air, shower dan permasalahan sanitair lain.',
                'icon_url' => '/icons/jagoan-sanitair.svg',
                'price_full_day' => 259000,
                'price_morning' => 199000,
                'price_afternoon' => 199000,
                'service_type' => 'daily',
                'sort_order' => 14,
            ],
            [
                'code' => 'JAGOAN_ANGKAT',
                'name' => 'Jagoan Angkat',
                'slug' => 'jagoan-angkat',
                'description' => 'Untuk keperluan mengangkat barang-barang rumahmu.',
                'icon_url' => '/icons/jagoan-angkat.svg',
                'price_full_day' => 209000,
                'price_morning' => 163000,
                'price_afternoon' => 163000,
                'service_type' => 'daily',
                'sort_order' => 15,
            ],
            [
                'code' => 'JAGOAN_LISTRIK_PERAPIHAN',
                'name' => 'Jagoan Listrik Perapihan',
                'slug' => 'jagoan-listrik-perapihan',
                'description' => 'Bongkar, perbaiki kabel listrik dan rapikan.',
                'icon_url' => '/icons/jagoan-listrik-perapihan.svg',
                'price_full_day' => 259000,
                'price_morning' => 199000,
                'price_afternoon' => 199000,
                'service_type' => 'daily',
                'sort_order' => 16,
            ],
            [
                'code' => 'JAGOAN_PIPA_PERAPIHAN',
                'name' => 'Jagoan Pipa Perapihan',
                'slug' => 'jagoan-pipa-perapihan',
                'description' => 'Bongkar, perbaiki pipa dan rapikan.',
                'icon_url' => '/icons/jagoan-pipa-perapihan.svg',
                'price_full_day' => 299000,
                'price_morning' => 239000,
                'price_afternoon' => 239000,
                'service_type' => 'daily',
                'sort_order' => 17,
            ],
        ];

        foreach ($services as $service) {
            Service::updateOrCreate(
                ['code' => $service['code']],
                array_merge($service, ['is_active' => true])
            );
        }
    }
}
